IT_FOR_COMPUTER = 'IT'
IT_FOR_HUMAN = 'IT / SW'
ENGLISH_FOR_COMPUTER = 'ENG'
ENGLISH_FOR_HUMAN = 'English'
ETC_FOR_COMPUTER = 'ETC'
ETC_FOR_HUMAN = 'Etc'

POST_MAIN_CHOICES = [
    (IT_FOR_COMPUTER, IT_FOR_HUMAN),
    (ENGLISH_FOR_COMPUTER, ENGLISH_FOR_HUMAN),
    (ETC_FOR_COMPUTER, ETC_FOR_HUMAN),
]

CATEGORY_NAME_PAIR = {
    IT_FOR_COMPUTER: IT_FOR_HUMAN,
    ENGLISH_FOR_COMPUTER: ENGLISH_FOR_HUMAN,
    ETC_FOR_COMPUTER: ETC_FOR_HUMAN
}
POST_CATEGORIES = {
    IT_FOR_COMPUTER: ['Android', 'Arduino', 'Django'],
    ETC_FOR_COMPUTER: ['Reading'],
}
